#!/bin/bash
#SBATCH -c 1
#SBATCH -t 0-08:00
#SBATCH -p short
#SBATCH --output=/n/data1/hsph/biostat/celehs/lab/kez641/DORM/simu/simu_11032025/out/CondA_L5_73.out
#SBATCH --error=/n/data1/hsph/biostat/celehs/lab/kez641/DORM/simu/simu_11032025/err/CondA_L5_73.err
#SBATCH --mem=2G
#SBATCH --job-name=CondA_L5_73

# Load required modules
module load gcc/14.2.0 R/4.4.2

# Change to project root directory
cd /n/data1/hsph/biostat/celehs/lab/kez641/DORM

# Run simulation script
Rscript /n/data1/hsph/biostat/celehs/lab/kez641/DORM/simu/NewSimu_CondA_L5.R 73
