#!/bin/bash
#SBATCH -c 1
#SBATCH -t 0-10:00
#SBATCH -p short
#SBATCH --output=/n/data1/hsph/biostat/celehs/lab/kez641/DORM/simu/simu_10242025/out/CondA_L5_42.out
#SBATCH --error=/n/data1/hsph/biostat/celehs/lab/kez641/DORM/simu/simu_10242025/err/CondA_L5_42.err
#SBATCH --mem=2G
#SBATCH --job-name=CondA_L5_42

# Load required modules
module load gcc/14.2.0 R/4.4.2

# Change to project root directory
cd /n/data1/hsph/biostat/celehs/lab/kez641/DORM

# Run simulation script
Rscript /n/data1/hsph/biostat/celehs/lab/kez641/DORM/simu/NewSimu_CondA_L5.R 42
